### ISSUE TITLE
static_file_info and _WIN32

### ISSUE THREAD

**Issue by epajarre** [mrozigor/crow#52]
Hi,

I met a problem while compiling on Windows:

on http_response.h the static_file_info is only defined if !defined(_WIN32)

http_connection.h uses it without _WIN32 checking

also app.h calls set_static_file info if CROW_DISABLE_STATIC_DIR is not defined

It was not immediately obvious to me, why the static_file_info part is disabled on _WIN32 compile.
The code compiles with Microsoft Visual studio, thus the easiest way to avoid the problem was to remove the condition in http_response.h  I should understand it first though...

Eero

**Comment by epajarre** [comment]
On my (very limited) testing so far, static_file stuff has worked on windows. I tested with a small text file, and a large .zip file.

**Comment by The-EDev** [comment]
The original static file implementation used `sendfile` and `stat` commnads. `sendfile` is a Unix only command. hence why the system was disabled on windows.

The current implementation does not use `sendfile` but it does use `stat` and I wasn't sure at the time if that was available on windows.

The code in app.h was developed much later, and I did overlook the whole `!defined(_WIN32)` part.

Since you said testing actually worked this means that `stat` is available for windows, and therefore the entire check is unnecessary.

I will get on it ASAP, or if you would like you can open a PR removing the `_WIN32` checks in `http_connection.h` and `http_response.h`.

**Comment by epajarre** [comment]
PR created, I created a separate PR for changing couple of uint to unsigned. I need both of these in order to compile on my Windows system, but I thought it is cleaner to keep them separate

**Comment by The-EDev** [comment]
Thanks, I'm checking them out right now.
